front_image: ../mypic.jpeg
resume: ../Rahul_Pandey_Resume.pdf
title: Rahul Pandey
title_temp: Rahul Pandey
description: PhD IT (2018-Present)
university: George Mason University
area: Social Computing | Intent Mining | Web Mining | Behavior Modeling
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
scholar_url: publications.html