title: <img src="../mypic.jpeg" alt="" width="80%" /><br>Rahul Pandey
description: PhD IT (2018-Present)<br>George Mason University <hr>Social Computing | Intent Modeling | Natural Language Understanding
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal